# Generated by Django 4.2.30 on 2026-04-23 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_money', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='缴费总金额')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name='缴费时间')),
                ('status', models.CharField(choices=[('unpaid', '未缴费'), ('paid', '已缴费')], default='unpaid', max_length=10, verbose_name='缴费状态')),
            ],
            options={
                'verbose_name': '缴费记录',
                'verbose_name_plural': '缴费记录',
            },
        ),
    ]
