# Generated by Django 4.2.30 on 2026-04-23 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dormitory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_time', models.DateTimeField(blank=True, null=True, verbose_name='实际报到时间')),
                ('status', models.CharField(choices=[('pending', '待报到'), ('completed', '已完成报到'), ('cancel', '报到驳回')], default='pending', max_length=20, verbose_name='报到状态')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='管理员备注')),
                ('dorm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dormitory.dormitory', verbose_name='分配宿舍')),
            ],
            options={
                'verbose_name': '新生报到记录',
                'verbose_name_plural': '新生报到记录',
            },
        ),
    ]
