# Generated by Django 4.2.30 on 2026-04-23 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dormitory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(max_length=10, verbose_name='楼栋号')),
                ('room_num', models.CharField(max_length=10, verbose_name='房间号')),
                ('total_bed', models.IntegerField(default=4, verbose_name='总床位数')),
                ('remain_bed', models.IntegerField(default=4, verbose_name='剩余可用床位')),
            ],
            options={
                'verbose_name': '宿舍信息',
                'verbose_name_plural': '宿舍信息',
                'unique_together': {('building', 'room_num')},
            },
        ),
    ]
